require("configs.settings")
require("plugins.plugins")
require("plugins.projects")
require("plugins.options")
require("plugins.whichkey")
require("plugins.toggleterm")
require("plugins.nvim-tree")
require("plugins.telescope")
require("plugins.bufferline")
require("plugins.comments")
require("plugins.gitsigns")
require("plugins.autopairs")
require("plugins.treesitter")
require("plugins.cmp")
require("plugins.leap")
-- require("plugins.lsp")
-- require("plugins.navigator")
require("plugins.lsp_signature")
require("configs.mappings")
require("plugins.alpha")
-- require("plugins.cheatsheet")
require("plugins.lualine_conf")
require("plugins.lsp_stuff")
-- require("plugins.rust_tools")

