require("configs.settings")
require("plugins.plugins")
require("plugins.projects")
require("plugins.options")
require("plugins.whichkey")
require("plugins.toggleterm")
require("plugins.ntree")
require("plugins.telescope")
require("plugins.bufferline")
require("plugins.heirline")
require("plugins.comments")
require("plugins.gitsigns")
require("plugins.autopairs")
require("plugins.treesitter")
require("plugins.leap")
require("configs.mappings")
require("plugins.alpha")
-- require("plugins.winbar")

--------- LSP RELATED
require("plugins.lsp_stuff")
require("plugins.lsp_signature")
require("plugins.cmp")
require("plugins.lsp")

